ALTER TABLE MIS_EMR_AE ADD (ECG_MONITOR  NUMBER(4));

ALTER TABLE MIS_EMR_MDFPRVS ADD (OBJECTID  VARCHAR2(20 BYTE));

ALTER TABLE MIS_EMR_MDFPRVS ADD (OBJECTTYPE  NUMBER(10));

ALTER TABLE MIS_EMR_MDFREQ ADD (ORG_ID  VARCHAR2(16 BYTE));

ALTER TABLE MIS_EMR_MDFPRVS ADD (REVIEWLEVEL  NUMBER(10));

ALTER TABLE MIS_EMR_MDFPRVS ADD (TYPE  VARCHAR2(20 BYTE));


COMMENT ON COLUMN MIS_EMR_AE.ECG_LEAD IS '心电图导联';

COMMENT ON COLUMN MIS_EMR_AE.ECG_MONITOR IS '心电监护情况';

COMMENT ON TABLE MIS_EMR_CMPLT_TEMPLATE IS 'MIS_电子病历_模板表';

COMMENT ON COLUMN MIS_EMR_CMPLT_TEMPLATE.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN MIS_EMR_CMPLT_TEMPLATE.CREATE_USERID IS '创建人';

COMMENT ON COLUMN MIS_EMR_CMPLT_TEMPLATE.LAST_MODIFY_TIME IS '最后更新时间';

COMMENT ON COLUMN MIS_EMR_CMPLT_TEMPLATE.MODIFY_USERID IS '最后更新人';

COMMENT ON COLUMN MIS_EMR_CMPLT_TEMPLATE.NAME IS '模板名称';

COMMENT ON COLUMN MIS_EMR_CMPLT_TEMPLATE.TMPL_TYPE IS '模板类型。0 公共模板，1 私人模板';

COMMENT ON COLUMN MIS_EMR_CMPLT_TEMPLATE.XZBM IS '行政编码';

COMMENT ON COLUMN MIS_EMR_MDFREQ.ORG_ID IS '机构代码';

COMMENT ON COLUMN MIS_EMR_QC_SUMMARY.FULLCREDIT_EMR_SUM IS '满分病例数';

COMMENT ON COLUMN MIS_EMR_QC_SUMMARY.LIGHT_EMR_SUM IS '病情轻病历数';

COMMENT ON COLUMN MIS_EMR_QC_SUMMARY.MEDIUM_EMR_SUM IS '病情中病历数';


ALTER TABLE MIS_EMR_MDFPRVS MODIFY(FLAG NUMBER(10));

ALTER TABLE MIS_EMR_MDFPRVS MODIFY(FLAG  DEFAULT NULL);

ALTER TABLE MIS_EMR_MDFPRVS MODIFY(MEMBERID VARCHAR2(255 BYTE));


