package com.zxit.wbss.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 */
@WebService(name = "lbsHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LbsHttpPost {

    /**
     * �ֻ��ַ��λ {"LSH":"123","Phone":"15298xxxxxx","Name":"Test"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RequestLocation")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String requestLocation(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * �������нӿ� {"LSH":"123","Phone":"15298xxxxxx","Content":"123456"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String mt(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * �˻����/�û�id��ѯ�ӿ� {"cmd":"balance"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String query(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * ��ѯ״̬����ӿ� {"userid":"userid"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getReport(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * ��ѯ���ж��Žӿ� {"userid":"userid"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getMO(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * ����LSH��ȡ������Ϣ
     *
     * @param lsh
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GET_SP_PRES_ACCEPT_INFO")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getSPPRESACCEPTINFO(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LSH") String lsh);

    /**
     * ����LSH��ȡ������Ϣ
     *
     * @param lsh
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_AMBUL_OUTD_INFO")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String spGETAMBULOUTDINFO(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LSH") String lsh);

    /**
     * ����CLID��ȡ������Ƶ�ն�
     *
     * @param clid
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_EMT_INFO")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String spGETEMTINFO(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CLID") String clid);

    /**
     * ��ȡ�����б�
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Get_All_CLLB_INFO")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getAllCLLBINFO();

    /**
     * ��ȡ�����ն��б����ͼ
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_ALL_TerminalDB_INFO")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String spGETALLTerminalDBINFO();

    /**
     * ��ȡ����Զ��ָ������
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Get_All_REQUEST_INFO")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getAllREQUESTINFO();

    /**
     * ��ȡ����δ���Զ��ָ������
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Get_All_CONFERENCE_INFO")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getAllCONFERENCEINFO();

    /**
     * ����������Ƶ�����
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RMG_INSERT_CONFRENCE")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String rmgINSERTCONFRENCE(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * ��������Զ��ָ�������¼
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "INSERT_TMG_REQUEST")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String insertTMGREQUEST(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * ����Զ��ָ������¼��
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_UPDATE_SESSIONS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String spUPDATESESSIONS(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * ����Զ��ָ��ָ�����
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RMG_INSERT_ADVICE")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String rmgINSERTADVICE(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * Զ��ҽѧָ������ {"userid":"userid"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String remoteRequire(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "msg") String msg);

    /**
     * @param id
     * @param password
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Check_Sys_Member_Info")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String checkSysMemberInfo(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "id") String id,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "password") String password);

    /**
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Get_All_V_ORG_INFO")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String getAllVORGINFO();

    /**
     * ����ʱ�䷶Χ��ȡ��Χ�����л���
     *
     * @param startTime
     * @param endTime
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_CONFERENCE_PERIOD")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String spGETCONFERENCEPERIOD(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "startTime") String startTime,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endTime") String endTime);

    /**
     * �������ID�鿴���вμӻ������
     *
     * @param conferenceId
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_CONFERENCE_SESSIONS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String spGETCONFERENCESESSIONS(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "conferenceId") String conferenceId);

}
