package com.zxit.wbss.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 */
@WebService(name = "lbsSoap", targetNamespace = "http://tempuri.org/")
public interface LbsSoap {

    /**
     * �ֻ��ַ��λ {"LSH":"123","Phone":"15298xxxxxx","Name":"Test"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RequestLocation", action = "http://tempuri.org/RequestLocation")
    @WebResult(name = "RequestLocationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestLocation", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.RequestLocation")
    @ResponseWrapper(localName = "RequestLocationResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.RequestLocationResponse")
    public String requestLocation(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * �������нӿ� {"LSH":"123","Phone":"15298xxxxxx","Content":"123456"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/mt")
    @WebResult(name = "mtResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "mt", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.Mt")
    @ResponseWrapper(localName = "mtResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.MtResponse")
    public String mt(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * �˻����/�û�id��ѯ�ӿ� {"cmd":"balance"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/query")
    @WebResult(name = "queryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "query", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.QueryResponse")
    public String query(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * ��ѯ״̬����ӿ� {"userid":"userid"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getReport")
    @WebResult(name = "getReportResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getReport", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetReport")
    @ResponseWrapper(localName = "getReportResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetReportResponse")
    public String getReport(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * ��ѯ���ж��Žӿ� {"userid":"userid"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getMO")
    @WebResult(name = "getMOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getMO", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetMO")
    @ResponseWrapper(localName = "getMOResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetMOResponse")
    public String getMO(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * ����LSH��ȡ������Ϣ
     *
     * @param lsh
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GET_SP_PRES_ACCEPT_INFO", action = "http://tempuri.org/GET_SP_PRES_ACCEPT_INFO")
    @WebResult(name = "GET_SP_PRES_ACCEPT_INFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GET_SP_PRES_ACCEPT_INFO", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GETSPPRESACCEPTINFO")
    @ResponseWrapper(localName = "GET_SP_PRES_ACCEPT_INFOResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GETSPPRESACCEPTINFOResponse")
    public String getSPPRESACCEPTINFO(
            @WebParam(name = "LSH", targetNamespace = "http://tempuri.org/") String lsh);

    /**
     * ����LSH��ȡ������Ϣ
     *
     * @param lsh
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_AMBUL_OUTD_INFO", action = "http://tempuri.org/SP_GET_AMBUL_OUTD_INFO")
    @WebResult(name = "SP_GET_AMBUL_OUTD_INFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SP_GET_AMBUL_OUTD_INFO", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETAMBULOUTDINFO")
    @ResponseWrapper(localName = "SP_GET_AMBUL_OUTD_INFOResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETAMBULOUTDINFOResponse")
    public String spGETAMBULOUTDINFO(
            @WebParam(name = "LSH", targetNamespace = "http://tempuri.org/") String lsh);

    /**
     * ����CLID��ȡ������Ƶ�ն�
     *
     * @param clid
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_EMT_INFO", action = "http://tempuri.org/SP_GET_EMT_INFO")
    @WebResult(name = "SP_GET_EMT_INFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SP_GET_EMT_INFO", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETEMTINFO")
    @ResponseWrapper(localName = "SP_GET_EMT_INFOResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETEMTINFOResponse")
    public String spGETEMTINFO(
            @WebParam(name = "CLID", targetNamespace = "http://tempuri.org/") String clid);

    /**
     * ��ȡ�����б�
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Get_All_CLLB_INFO", action = "http://tempuri.org/Get_All_CLLB_INFO")
    @WebResult(name = "Get_All_CLLB_INFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_All_CLLB_INFO", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetAllCLLBINFO")
    @ResponseWrapper(localName = "Get_All_CLLB_INFOResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetAllCLLBINFOResponse")
    public String getAllCLLBINFO();

    /**
     * ��ȡ�����ն��б����ͼ
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_ALL_TerminalDB_INFO", action = "http://tempuri.org/SP_GET_ALL_TerminalDB_INFO")
    @WebResult(name = "SP_GET_ALL_TerminalDB_INFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SP_GET_ALL_TerminalDB_INFO", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETALLTerminalDBINFO")
    @ResponseWrapper(localName = "SP_GET_ALL_TerminalDB_INFOResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETALLTerminalDBINFOResponse")
    public String spGETALLTerminalDBINFO();

    /**
     * ��ȡ����Զ��ָ������
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Get_All_REQUEST_INFO", action = "http://tempuri.org/Get_All_REQUEST_INFO")
    @WebResult(name = "Get_All_REQUEST_INFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_All_REQUEST_INFO", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetAllREQUESTINFO")
    @ResponseWrapper(localName = "Get_All_REQUEST_INFOResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetAllREQUESTINFOResponse")
    public String getAllREQUESTINFO();

    /**
     * ��ȡ����δ���Զ��ָ������
     *
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Get_All_CONFERENCE_INFO", action = "http://tempuri.org/Get_All_CONFERENCE_INFO")
    @WebResult(name = "Get_All_CONFERENCE_INFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_All_CONFERENCE_INFO", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetAllCONFERENCEINFO")
    @ResponseWrapper(localName = "Get_All_CONFERENCE_INFOResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetAllCONFERENCEINFOResponse")
    public String getAllCONFERENCEINFO();

    /**
     * ����������Ƶ�����
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RMG_INSERT_CONFRENCE", action = "http://tempuri.org/RMG_INSERT_CONFRENCE")
    @WebResult(name = "RMG_INSERT_CONFRENCEResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMG_INSERT_CONFRENCE", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.RMGINSERTCONFRENCE")
    @ResponseWrapper(localName = "RMG_INSERT_CONFRENCEResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.RMGINSERTCONFRENCEResponse")
    public String rmgINSERTCONFRENCE(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * ��������Զ��ָ�������¼
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "INSERT_TMG_REQUEST", action = "http://tempuri.org/INSERT_TMG_REQUEST")
    @WebResult(name = "INSERT_TMG_REQUESTResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "INSERT_TMG_REQUEST", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.INSERTTMGREQUEST")
    @ResponseWrapper(localName = "INSERT_TMG_REQUESTResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.INSERTTMGREQUESTResponse")
    public String insertTMGREQUEST(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * ����Զ��ָ������¼��
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_UPDATE_SESSIONS", action = "http://tempuri.org/SP_UPDATE_SESSIONS")
    @WebResult(name = "SP_UPDATE_SESSIONSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SP_UPDATE_SESSIONS", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPUPDATESESSIONS")
    @ResponseWrapper(localName = "SP_UPDATE_SESSIONSResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPUPDATESESSIONSResponse")
    public String spUPDATESESSIONS(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * ����Զ��ָ��ָ�����
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "RMG_INSERT_ADVICE", action = "http://tempuri.org/RMG_INSERT_ADVICE")
    @WebResult(name = "RMG_INSERT_ADVICEResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RMG_INSERT_ADVICE", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.RMGINSERTADVICE")
    @ResponseWrapper(localName = "RMG_INSERT_ADVICEResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.RMGINSERTADVICEResponse")
    public String rmgINSERTADVICE(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * Զ��ҽѧָ������ {"userid":"userid"}
     *
     * @param msg
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/remoteRequire")
    @WebResult(name = "remoteRequireResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "remoteRequire", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.RemoteRequire")
    @ResponseWrapper(localName = "remoteRequireResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.RemoteRequireResponse")
    public String remoteRequire(
            @WebParam(name = "msg", targetNamespace = "http://tempuri.org/") String msg);

    /**
     * @param id
     * @param password
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Check_Sys_Member_Info", action = "http://tempuri.org/Check_Sys_Member_Info")
    @WebResult(name = "Check_Sys_Member_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Check_Sys_Member_Info", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.CheckSysMemberInfo")
    @ResponseWrapper(localName = "Check_Sys_Member_InfoResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.CheckSysMemberInfoResponse")
    public String checkSysMemberInfo(
            @WebParam(name = "id", targetNamespace = "http://tempuri.org/") String id,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password);

    /**
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Get_All_V_ORG_INFO", action = "http://tempuri.org/Get_All_V_ORG_INFO")
    @WebResult(name = "Get_All_V_ORG_INFOResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_All_V_ORG_INFO", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetAllVORGINFO")
    @ResponseWrapper(localName = "Get_All_V_ORG_INFOResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.GetAllVORGINFOResponse")
    public String getAllVORGINFO();

    /**
     * ����ʱ�䷶Χ��ȡ��Χ�����л���
     *
     * @param startTime
     * @param endTime
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_CONFERENCE_PERIOD", action = "http://tempuri.org/SP_GET_CONFERENCE_PERIOD")
    @WebResult(name = "SP_GET_CONFERENCE_PERIODResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SP_GET_CONFERENCE_PERIOD", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETCONFERENCEPERIOD")
    @ResponseWrapper(localName = "SP_GET_CONFERENCE_PERIODResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETCONFERENCEPERIODResponse")
    public String spGETCONFERENCEPERIOD(
            @WebParam(name = "startTime", targetNamespace = "http://tempuri.org/") String startTime,
            @WebParam(name = "endTime", targetNamespace = "http://tempuri.org/") String endTime);

    /**
     * �������ID�鿴���вμӻ������
     *
     * @param conferenceId
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SP_GET_CONFERENCE_SESSIONS", action = "http://tempuri.org/SP_GET_CONFERENCE_SESSIONS")
    @WebResult(name = "SP_GET_CONFERENCE_SESSIONSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SP_GET_CONFERENCE_SESSIONS", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETCONFERENCESESSIONS")
    @ResponseWrapper(localName = "SP_GET_CONFERENCE_SESSIONSResponse", targetNamespace = "http://tempuri.org/", className = "com.zxit.wbss.soap.SPGETCONFERENCESESSIONSResponse")
    public String spGETCONFERENCESESSIONS(
            @WebParam(name = "conferenceId", targetNamespace = "http://tempuri.org/") String conferenceId);

}
