ALTER TABLE MIS_EMR_PE
 DROP PRIMARY KEY CASCADE;

DROP TABLE MIS_EMR_PE CASCADE CONSTRAINTS;

CREATE TABLE MIS_EMR_PE
(
  ID                VARCHAR2(20 BYTE)           NOT NULL,
  T_TEST            NUMBER(4),
  T                 NUMBER(4,1),
  P_TEST            NUMBER(4),
  P                 NUMBER(4),
  R_TEST            NUMBER(4),
  R                 NUMBER(4),
  BP_TEST           NUMBER(4),
  BP_L              NUMBER(4),
  BP_H              NUMBER(4),
  POSTURE           NUMBER(4),
  CONSCIOUS         NUMBER(4),
  SKIN              NUMBER(4),
  CYANOSIS          NUMBER(4),
  HN_EYE_TEST_L     NUMBER(4),
  HN_EYE_L          NUMBER(5,1),
  HN_PLR_L          NUMBER(4),
  HN_EYE_TEST_R     NUMBER(4),
  HN_EYE_R          NUMBER(5,1),
  HN_PLR_R          NUMBER(4),
  HEAD_NECK         VARCHAR2(512 BYTE),
  CHEST             VARCHAR2(512 BYTE),
  LUNG              VARCHAR2(512 BYTE),
  HEART             VARCHAR2(512 BYTE),
  ABDOMEN           VARCHAR2(512 BYTE),
  LIMB              VARCHAR2(512 BYTE),
  SPINE             VARCHAR2(512 BYTE),
  NERVE_REFLEX      VARCHAR2(512 BYTE),
  PE_OTHERS         VARCHAR2(512 BYTE),
  CREATE_TIME       DATE                        NOT NULL,
  LAST_MODIFY_TIME  DATE,
  XZBM              NUMBER(8)                   DEFAULT 410100
)
NOCOMPRESS 
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
PARTITION BY RANGE (CREATE_TIME)
INTERVAL( NUMTOYMINTERVAL(3,'MONTH'))
(  
  PARTITION P1 VALUES LESS THAN (TO_DATE(' 2016-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MAXSIZE          UNLIMITED
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
)
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MIS_EMR_PE IS 'MIS_电子病历_体格检查';

COMMENT ON COLUMN MIS_EMR_PE.ID IS '患者ID';

COMMENT ON COLUMN MIS_EMR_PE.T_TEST IS '体温是否检查';

COMMENT ON COLUMN MIS_EMR_PE.T IS '体温。单位：℃';

COMMENT ON COLUMN MIS_EMR_PE.P_TEST IS '脉率是否检查';

COMMENT ON COLUMN MIS_EMR_PE.P IS '脉率。单位：次/分';

COMMENT ON COLUMN MIS_EMR_PE.R_TEST IS '呼吸是否检查';

COMMENT ON COLUMN MIS_EMR_PE.R IS '呼吸频率。单位：次/分';

COMMENT ON COLUMN MIS_EMR_PE.BP_TEST IS 'BP检查情况';

COMMENT ON COLUMN MIS_EMR_PE.BP_L IS '血压低值。单位：mmHg';

COMMENT ON COLUMN MIS_EMR_PE.BP_H IS '血压高值。单位：mmHg';

COMMENT ON COLUMN MIS_EMR_PE.POSTURE IS '体位';

COMMENT ON COLUMN MIS_EMR_PE.CONSCIOUS IS '神志';

COMMENT ON COLUMN MIS_EMR_PE.SKIN IS '皮肤';

COMMENT ON COLUMN MIS_EMR_PE.CYANOSIS IS '口唇紫绀。存储有无编码';

COMMENT ON COLUMN MIS_EMR_PE.HN_EYE_TEST_L IS '头颈_瞳孔是否检查_左';

COMMENT ON COLUMN MIS_EMR_PE.HN_EYE_L IS '头颈_瞳孔_左。单位：mm';

COMMENT ON COLUMN MIS_EMR_PE.HN_PLR_L IS '头颈_瞳孔对光反射_左';

COMMENT ON COLUMN MIS_EMR_PE.HN_EYE_TEST_R IS '头颈_瞳孔是否检查_右';

COMMENT ON COLUMN MIS_EMR_PE.HN_EYE_R IS '头颈_瞳孔_右。单位：mm';

COMMENT ON COLUMN MIS_EMR_PE.HN_PLR_R IS '头颈_瞳孔对光反射_右';

COMMENT ON COLUMN MIS_EMR_PE.HEAD_NECK IS '头颈部';

COMMENT ON COLUMN MIS_EMR_PE.CHEST IS '胸部';

COMMENT ON COLUMN MIS_EMR_PE.LUNG IS '肺部';

COMMENT ON COLUMN MIS_EMR_PE.HEART IS '心脏';

COMMENT ON COLUMN MIS_EMR_PE.ABDOMEN IS '腹部';

COMMENT ON COLUMN MIS_EMR_PE.LIMB IS '四肢';

COMMENT ON COLUMN MIS_EMR_PE.SPINE IS '脊柱';

COMMENT ON COLUMN MIS_EMR_PE.NERVE_REFLEX IS '神经反射';

COMMENT ON COLUMN MIS_EMR_PE.PE_OTHERS IS '其他';

COMMENT ON COLUMN MIS_EMR_PE.CREATE_TIME IS '创建时间';

COMMENT ON COLUMN MIS_EMR_PE.LAST_MODIFY_TIME IS '最后更新时间';

COMMENT ON COLUMN MIS_EMR_PE.XZBM IS '行政编码';



CREATE UNIQUE INDEX PK_MIS_EMR_PE ON MIS_EMR_PE
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE MIS_EMR_PE ADD (
  CONSTRAINT PK_MIS_EMR_PE
  PRIMARY KEY
  (ID)
  USING INDEX PK_MIS_EMR_PE
  ENABLE VALIDATE);
